from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from . import store as analyzer_store

WAREHOUSE_SCHEMA = """
CREATE TABLE IF NOT EXISTS dim_event_type (
    event_type text PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS dim_org (
    org_uid text PRIMARY KEY,
    name text
);
CREATE TABLE IF NOT EXISTS dim_person (
    person_key text PRIMARY KEY,
    name text
);
CREATE TABLE IF NOT EXISTS dim_plz (
    plz text PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS dim_canton (
    canton text PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS fact_event (
    id integer PRIMARY KEY AUTOINCREMENT,
    publication_id text NOT NULL,
    published_at text NOT NULL,
    event_type text NOT NULL,
    rule_id text,
    org_uid text,
    person_key text,
    plz text,
    canton text,
    role text,
    signing text,
    payload_json text
);
CREATE INDEX IF NOT EXISTS idx_fact_person ON fact_event(person_key, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_plz ON fact_event(plz, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_canton ON fact_event(canton, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_org ON fact_event(org_uid, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_type ON fact_event(event_type, published_at);
"""

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS dim_event_type (
    event_type text PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS dim_org (
    org_uid text PRIMARY KEY,
    name text
);
CREATE TABLE IF NOT EXISTS dim_person (
    person_key text PRIMARY KEY,
    name text
);
CREATE TABLE IF NOT EXISTS dim_plz (
    plz text PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS dim_canton (
    canton text PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS fact_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id text NOT NULL,
    published_at date NOT NULL,
    event_type text NOT NULL,
    rule_id text,
    org_uid text,
    person_key text,
    plz text,
    canton text,
    role text,
    signing text,
    payload_json jsonb
);
CREATE INDEX IF NOT EXISTS idx_fact_person ON fact_event(person_key, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_plz ON fact_event(plz, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_canton ON fact_event(canton, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_org ON fact_event(org_uid, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_type ON fact_event(event_type, published_at);
"""


def connect(path: Path) -> sqlite3.Connection:
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    conn.executescript(WAREHOUSE_SCHEMA)
    return conn


def replay_from_analyzer(analyzer_conn: sqlite3.Connection, warehouse_conn: sqlite3.Connection) -> int:
    warehouse_conn.execute("DELETE FROM fact_event")
    rows = analyzer_store.all_events(analyzer_conn)
    for row in rows:
        payload = json.loads(row["payload_json"] or "{}")
        warehouse_conn.execute(
            """
            INSERT INTO fact_event (
                publication_id, published_at, event_type, rule_id, org_uid, person_key,
                plz, canton, role, signing, payload_json
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                row["publication_id"],
                row["published_at"],
                row["event_type"],
                row["rule_id"],
                row["org_uid"],
                row["person_key"],
                row["plz"],
                row["canton"],
                row["role"],
                row["signing"],
                row["payload_json"],
            ),
        )
        if row["event_type"]:
            warehouse_conn.execute(
                "INSERT OR IGNORE INTO dim_event_type(event_type) VALUES (?)",
                (row["event_type"],),
            )
        if row["org_uid"]:
            warehouse_conn.execute(
                "INSERT OR IGNORE INTO dim_org(org_uid, name) VALUES (?, ?)",
                (row["org_uid"], payload.get("name") or payload.get("to")),
            )
        if row["person_key"]:
            warehouse_conn.execute(
                "INSERT OR IGNORE INTO dim_person(person_key, name) VALUES (?, ?)",
                (row["person_key"], payload.get("name")),
            )
        if row["plz"]:
            warehouse_conn.execute("INSERT OR IGNORE INTO dim_plz(plz) VALUES (?)", (row["plz"],))
        if row["canton"]:
            warehouse_conn.execute(
                "INSERT OR IGNORE INTO dim_canton(canton) VALUES (?)",
                (row["canton"],),
            )
    warehouse_conn.commit()
    return len(rows)


def lens_timeline(conn: sqlite3.Connection, dimension: str, key: str) -> list[dict]:
    column = {
        "person": "person_key",
        "plz": "plz",
        "canton": "canton",
        "org": "org_uid",
        "event_type": "event_type",
    }.get(dimension)
    if column is None:
        raise ValueError(f"unknown lens {dimension}")
    rows = conn.execute(
        f"""
        SELECT published_at, event_type, publication_id, org_uid, person_key, plz, canton,
               role, signing, payload_json
        FROM fact_event
        WHERE {column} = ?
        ORDER BY published_at, publication_id
        """,
        (key,),
    ).fetchall()
    return [dict(r) for r in rows]


def lens_pulse(conn: sqlite3.Connection, dimension: str, key: str) -> list[dict]:
    column = {
        "person": "person_key",
        "plz": "plz",
        "canton": "canton",
        "org": "org_uid",
        "event_type": "event_type",
    }.get(dimension)
    if column is None:
        raise ValueError(f"unknown lens {dimension}")
    rows = conn.execute(
        f"""
        SELECT substr(published_at, 1, 7) AS month, event_type, COUNT(*) AS n
        FROM fact_event
        WHERE {column} = ?
        GROUP BY 1, 2
        ORDER BY 1, 2
        """,
        (key,),
    ).fetchall()
    return [dict(r) for r in rows]


def related_org_events(conn: sqlite3.Connection, person_key: str) -> list[dict]:
    """All facts for orgs that this person appears in (firma-Lebenslauf rund um die Person)."""
    rows = conn.execute(
        """
        SELECT f.published_at, f.event_type, f.publication_id, f.org_uid, f.person_key,
               f.plz, f.canton, f.role, f.signing, f.payload_json
        FROM fact_event f
        WHERE f.org_uid IN (
            SELECT DISTINCT org_uid FROM fact_event
            WHERE person_key = ? AND org_uid IS NOT NULL
        )
        ORDER BY f.published_at, f.publication_id
        """,
        (person_key,),
    ).fetchall()
    return [dict(r) for r in rows]


def plz_people(conn: sqlite3.Connection, plz: str) -> list[dict]:
    rows = conn.execute(
        """
        SELECT person_key, COUNT(*) AS n
        FROM fact_event
        WHERE plz = ? AND person_key IS NOT NULL
        GROUP BY person_key
        ORDER BY n DESC
        """,
        (plz,),
    ).fetchall()
    return [dict(r) for r in rows]
