CREATE TABLE IF NOT EXISTS dim_event_type (
    event_type text PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS dim_org (
    org_uid text PRIMARY KEY,
    name text
);
CREATE TABLE IF NOT EXISTS dim_person (
    person_key text PRIMARY KEY,
    name text
);
CREATE TABLE IF NOT EXISTS dim_plz (
    plz text PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS dim_canton (
    canton text PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS fact_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id text NOT NULL,
    published_at date NOT NULL,
    event_type text NOT NULL,
    rule_id text,
    org_uid text,
    person_key text,
    plz text,
    canton text,
    role text,
    signing text,
    payload_json jsonb
);
CREATE INDEX IF NOT EXISTS idx_fact_person ON fact_event(person_key, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_plz ON fact_event(plz, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_canton ON fact_event(canton, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_org ON fact_event(org_uid, published_at);
CREATE INDEX IF NOT EXISTS idx_fact_type ON fact_event(event_type, published_at);
